---
- hosts: all

  roles:

    - environment-core
    - environment-apache
    - environment-postgresql
    - environment-mongodb
    - environment-clojure
    - environment-selenium

  tasks:

    - name: Create database user                                 
      postgresql_user: name={{ item }} password={{ admin_password }} role_attr_flags=CREATEDB,SUPERUSER
      with_items:  
        - run
        - admin 
      sudo: yes
      sudo_user: postgres
      tags:
      - writing-hub
      - postgresql
      - run

    - name: Setup production databases
      postgresql_db: name={{ item }} owner=run
      with_items:
        - writing-hub
      sudo: yes
      sudo_user: postgres
      tags:
      - writing-hub
      - postgresql
      - run

    - name: Add node PPA
      apt_repository: repo='ppa:chris-lea/node.js' update_cache=yes
      sudo: yes

    - name: Install npm
      apt: pkg={{ item }}
      with_items:
      - nodejs
      - make
      - build-essential
      - g++
      sudo: yes

    - name: Install react tools
      npm: name={{ item }} global=yes
      with_items:
      - react-tools
      - jest-cli
      - gulp
      - vinyl-source-stream
      - browserify
      - reactify
      - glob
      sudo: yes

    - name: Copy upstart script
      copy: src=files/writing-hub-build.conf dest=/etc/init mode=0644
      notify:
      - Starts the gulp process to watch/build the writing-hub project
      sudo: yes

  handlers:

    - name: Starts the gulp process to watch/build the writing-hub project
      service: name=writing-hub-build state=restarted
      sudo: yes
