---
- hosts: all

  roles:

    - environment-core
    - environment-apache
    - environment-mongodb
    - environment-clojure
    - environment-selenium

  tasks:

    - name: Add redis PPA
      apt_repository: repo={{ item }}
      sudo: yes
      with_items:
      - ppa:chris-lea/redis-server
      - ppa:chris-lea/node.js

    - name: Install redis 
      apt: pkg=redis-server update_cache=yes
      sudo: yes

    - name: Install npm
      apt: pkg={{ item }}
      with_items:
      - nodejs
      - make
      - build-essential
      - g++
      sudo: yes

    - name: Install react tools
      npm: name={{ item }} global=yes
      with_items:
      - react-tools
      - jest-cli
      - gulp
      - vinyl-source-stream
      - browserify
      - reactify
      - glob
      sudo: yes

    - name: Copy upstart script
      copy: src=files/browser-client-build.conf dest=/etc/init mode=0644
      notify:
      - Starts the gulp process to watch/build the writing-hub project
      sudo: yes

  handlers:

    - name: Starts the gulp process to watch/build the writing-hub project
      service: name=browser-client-build state=restarted
      sudo: yes
