---
- hosts: all

  pre_tasks:

    - name: Add hosts references
      lineinfile: dest=/etc/hosts line="{{ item }}"
      with_items:
      - 127.0.0.1	redis
      - 127.0.0.1	mongodb
      sudo: yes

  roles:

    - environment-core
    - environment-clojure
    - environment-selenium
    - environment-docker
    - ./
