---
- hosts: all

  roles:

    - environment-core
    - environment-apache
    - environment-postgresql
    - environment-mongodb
    - environment-clojure
    - environment-selenium

  tasks:

    - name: Create database user                                 
      postgresql_user: name={{ item }} password={{ admin_password }} role_attr_flags=CREATEDB,SUPERUSER
      with_items:  
        - run
        - admin 
      sudo: yes
      sudo_user: postgres
      tags:
      - writing-hub
      - postgresql
      - run

    - name: Setup production databases
      postgresql_db: name={{ item }} owner=run
      with_items:
        - writing-hub
      sudo: yes
      sudo_user: postgres
      tags:
      - writing-hub
      - postgresql
      - run

    - name: Add node PPA
      apt_repository: repo='ppa:chris-lea/node.js' update_cache=yes
      sudo: yes

    - name: Install npm
      apt: pkg={{ item }}
      with_items:
      - nodejs
      - make
      - build-essential
      - g++
      sudo: yes

    - name: Install react tools
      npm: name={{ item }} global=yes
      with_items:
      - react-tools
      - jest-cli
      sudo: yes

    - name: Install react/react-bootstrap
      npm: name={{ item }} path=/home/vagrant/Documents/workspace/writing-hub/resources/public/js
      with_items:
      - react
      - react-bootstrap

    - name: Copy upstart script
      copy: src=files/jsx-watch-writing-hub.conf dest=/etc/init mode=0644
      notify:
      - Start watching for jsx changes
      sudo: yes

  handlers:

    - name: Start watching for jsx changes
      service: name=jsx-watch-writing-hub state=restarted
      sudo: yes
