
    - name: Get nodejs setup script
      get_url: url=https://deb.nodesource.com/setup_4.x dest=~/nodejs-installer
      sudo: yes
      tags:
      - writing-hub
      - development

    - name: Setup nodejs
      command: /bin/bash ~/nodejs-installer
      sudo: yes
      tags:
      - writing-hub
      - development

    - name: Install nodejs
      apt: pkg=nodejs
      sudo: yes
      tags:
      - writing-hub
      - development

    - name: Install gulp
      npm: name={{ item.name }} version={{ item.version }} global=yes
      sudo: yes
      with_items:
      - {name: gulp, version: 3.9.0}
      tags:
      - writing-hub
      - development

    - name: Copy upstart script
      copy: src=files/browser-client-build.conf dest=/etc/init mode=0644
      notify:
      - Starts the gulp process to watch/build the writing-hub project
      sudo: yes
      tags:
      - writing-hub
      - development
      - vagrant

    - name: Install python-pip
      apt: pkg=python-pip update_cache=yes
      sudo: yes
      tags:
      - writing-hub
      - development
      - vagrant

    - name: Install docker apt repository
      apt_repository: repo='deb https://get.docker.com/ubuntu docker main' state=present
      sudo: yes
      tags:
      - writing-hub
      - development
      - vagrant

    - name: Add docker apt key
      apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9
      sudo: yes
      tags:
      - writing-hub
      - development
      - vagrant

    - name: Install docker
      apt: name=lxc-docker update_cache=yes
      sudo: yes
      tags:
      - writing-hub
      - development
      - vagrant

    - name: Add vagrant user to docker group
      user: name=vagrant groups=docker append=yes
      sudo: yes
      tags:
      - writing-hub
      - development
      - vagrant

    - name: Install docker-compose
      pip: name=docker-compose
      sudo: yes
      tags:
      - writing-hub
      - development
      - vagrant

    - name: Copy upstart script for docker services
      copy: src=docker-services.conf dest=/etc/init/ mode=0644
      notify:
      - Restart docker-services
      sudo: yes
      tags:
      - writing-hub
      - development
      - vagrant
