
    - name: Starts the gulp process to watch/build the writing-hub project
      service: name=browser-client-build state=restarted
      sudo: yes

    - name: Restart docker-services
      service: name=docker-services state=restarted
      sudo: yes
